# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sot.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsot.proto\"\"\n\x11get_protoResponce\x12\r\n\x05proto\x18\x01 \x01(\t\"\x11\n\x0fget_protoRquest2:\n\x03SOT\x12\x33\n\tget_proto\x12\x10.get_protoRquest\x1a\x12.get_protoResponce\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GET_PROTORESPONCE']._serialized_start=13
  _globals['_GET_PROTORESPONCE']._serialized_end=47
  _globals['_GET_PROTORQUEST']._serialized_start=49
  _globals['_GET_PROTORQUEST']._serialized_end=66
  _globals['_SOT']._serialized_start=68
  _globals['_SOT']._serialized_end=126
# @@protoc_insertion_point(module_scope)
