# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Edited by NF-coder
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sot_pb2 as sot__pb2 # modified line

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SOTServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_active_proto = channel.unary_unary(
                '/SOTServer/get_active_proto',
                request_serializer=sot__pb2.get_active_protoRquest.SerializeToString,
                response_deserializer=sot__pb2.get_active_protoResponce.FromString,
                _registered_method=True)


class SOTServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_active_proto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SOTServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_active_proto': grpc.unary_unary_rpc_method_handler(
                    servicer.get_active_proto,
                    request_deserializer=sot__pb2.get_active_protoRquest.FromString,
                    response_serializer=sot__pb2.get_active_protoResponce.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SOTServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SOTServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SOTServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_active_proto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/SOTServer/get_active_proto',
            sot__pb2.get_active_protoRquest.SerializeToString,
            sot__pb2.get_active_protoResponce.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
